### ISSUE TITLE
Startup failure on docker , mongodb connection refused

### ISSUE THREAD

**Issue by CuriousDolphin** [IDEA-Research/deepdataspace#27]
Hello!
I got this error when starting DDS docker from docker compose with following configuration:
```
  deep_data_spaces:
    image: deepdataspace/dds
    ports:
      - 8765:8765
    command: "dds --quickstart -V"
    volumes:
      - ./dds:/dds/runtime
```

![image](https://github.com/IDEA-Research/deepdataspace/assets/36967518/ead626c4-fdc5-47cc-9526-6b417ac8c3b3)
![image](https://github.com/IDEA-Research/deepdataspace/assets/36967518/8e241ccc-893d-448a-9b0c-2f72f9408953)

Maybe I need to configure some environment variable related to mongo?
